name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo "Building..."
    - name: Test
      run: echo "Testing..."
    - name: Deploy
      run: echo "Deploying..."